# Generated by Django 3.2.9 on 2021-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=100)),
                ('from_currency_name', models.CharField(max_length=100)),
                ('to_currency_code', models.CharField(max_length=100)),
                ('to_currency_name', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('last_refreshed', models.DateTimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('ask_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('bid_price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
