# Generated by Django 2.2.12 on 2021-09-20 10:03

import auth.staff.models
from django.db import migrations, models
import labs.modelfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default=auth.staff.models.next_emp_id, max_length=16, unique=True)),
                ('mobile', labs.modelfield.PhoneNumberField(null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('public_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
